project_id = "gbotcdygsizmklsqgniu"

[functions.send-booking-notification]
verify_jwt = false

[functions.send-cancellation-notification]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.create-reservation]
verify_jwt = false
